# Generated by Django 6.0.3 on 2026-04-27 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donar_details",
            fields=[
                ("did", models.IntegerField(primary_key=True, serialize=False)),
                ("dname", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=5)),
                ("age", models.IntegerField()),
                ("phno", models.CharField(max_length=10)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("bloodgroup", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=100)),
                ("availability", models.CharField(default="Available", max_length=15)),
                ("last_donation_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Donation.donar_details",
                    ),
                ),
            ],
        ),
    ]
