# Generated by Django 6.0.3 on 2026-04-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Donation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donar_details",
            name="bloodgroup",
            field=models.CharField(max_length=20),
        ),
    ]
